name: coaching_app
description: Journal, Notes and AI Coaching App

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

  # To see which dependencies have newer
  # versions available, run `flutter pub outdated`.

  # To automatically upgrade your package dependencies to the latest versions
  # consider running `flutter pub upgrade --major-versions`.


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  flutter_svg: ^2.0.2
  bot_toast: ^4.0.3
  table_calendar: ^3.0.2
  image_picker: ^1.0.2
  lottie: ^2.6.0

  # firebase
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^15.1.0+1


  fluttertoast: ^8.2.2
  pin_code_fields: ^8.0.1

  flutter_quill: ^7.4.6

  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  dio: ^5.0.1

  flutter_native_splash: ^2.3.2
  intl: ^0.18.1
  flutter_image_compress: ^2.0.4
  cached_network_image: ^3.3.0

# dart run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/images/png/app-logo.png
  image_dark: assets/images/png/app-logo.png
  color: "#1c1b1b"
  color_dark: "#1c1b1b"
  fullscreen: true

  android_12:
    color: "#1c1b1b"
    color_dark: "#1c1b1b"
    fullscreen: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0 # command: 'flutter pub run change_app_package_name:main com.new.package.name'

#  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/png/
    - assets/images/svg/
